### ISSUE TITLE
Problem running 

### ISSUE THREAD

**Issue by ivan-gavran** [mpi-sws-rse/ltltalk-backend#1]
[Transferring issue by @saramohammadinejad from [interactive-synthesis repo](https://github.com/mpi-sws-rse/ltltalk-interactive-synthesis)

Hi,

When I run ./interactive/run @mode=ltltalk for the backend part I receive the following error:

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- execrunner (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./interactive/run:9:in `<main>'

I tried to resolve the error by installing other versions of ruby, but the issue still exists. Any suggestion?

Thanks,
Sara

**Comment by ivan-gavran** [comment]
Hi @saramohammadinejad,

It seems that you are missing the [execrunner](https://github.com/percyliang/fig/blob/master/lib/execrunner.rb) file. This should have been downloaded when pulling dependencies (step 2. from readme). Could you repeat the step and see if there is some problem downloading the folder `fig` (where the file should be)?

Ivan
